# Generated by Django 4.2.2 on 2023-08-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(upload_to='static/media/team_images/'),
        ),
    ]
